import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const html=()=>readFile('dist/index.html','utf8');
const script=()=>readFile('dist/maintainer/status.mjs','utf8');

test('status is a masthead tab and remains read-only',async()=>{const [h,s]=await Promise.all([html(),script()]);const header=h.match(/<header\b[^>]*>[\s\S]*?<\/header>/)?.[0]||'';assert.match(header,/id="maintainer-nav"[^>]*role="tablist"/);assert.match(header,/<button(?=[^>]*id="flashTab")(?=[^>]*role="tab")(?=[^>]*type="button")[^>]*>\s*Flash/);assert.match(header,/<button(?=[^>]*id="statusTab")(?=[^>]*role="tab")(?=[^>]*type="button")[^>]*>\s*Status/);assert.match(h,/status\.mjs/);assert.match(h,/id="flashView"[^>]*>/);assert.match(h,/id="statusView"[^>]*hidden/);assert.match(s,/current\.json/);assert.match(s,/manifest\.json/);assert.match(s,/provenance.*receipt|receipt.*provenance/);assert.doesNotMatch(s,/innerHTML|fetch\([^)]*https?:/)});
test('status labels snapshot, build and deployment independently',async()=>{const s=await script();assert.match(s,/Snapshot generated/);assert.match(s,/Build time/);assert.match(s,/Deployment time/);assert.match(s,/Not provided/)});
test('status renders an ordered accessible collapsible firmware list',async()=>{const s=await script();assert.match(s,/Supported firmware/);assert.match(s,/details/);assert.match(s,/summary/);for(const label of ['QuinLED Dig2Go','Athom ESP32-C3 controller','Waveshare ESP32-S3-Touch-AMOLED-2.16'])assert.match(s,new RegExp(label));assert.match(s,/hardware-tested|Hardware tested/);assert.match(s,/addEventListener\(['"]toggle/)});
test('status formats OTA slot objects without object coercion',async()=>{const s=await script();assert.match(s,/formatOtaSlot/);assert.match(s,/partition name|Partition name/);assert.match(s,/offset/);assert.match(s,/sizeBytes/);assert.doesNotMatch(s,/\[\$\{[^}]*otaSlot[^}]*\}\]/)});
test('status remains firmware and serial free and wraps hashes',async()=>{const [s,css]=await Promise.all([script(),readFile('dist/maintainer/status.css','utf8')]);assert.doesNotMatch(s,/navigator\.serial|firmware\/|\.bin/);assert.match(css,/overflow-wrap|word-break/);assert.match(css,/overflow-x/)});
test('status source and generated modules parse as executable JavaScript',async()=>{const {spawnSync}=await import('node:child_process');for(const file of ['easy-flash/maintainer/status.mjs','dist/maintainer/status.mjs']){const result=spawnSync(process.execPath,['--check',file],{encoding:'utf8'});assert.equal(result.status,0,`${file}: ${result.stderr}`)}});
test('status rejects unsafe immutable-release evidence paths',async()=>{const s=await script();const result=await import('../easy-flash/maintainer/status.mjs?path-test');const good='releases/abc123/provenance/build-receipt.json';assert.equal(result.validateReleaseRelativePath(good,{releaseId:'abc123',kind:'receipt'}),good);for(const bad of ['/releases/abc123/provenance/x','https://evil.test/x','releases/abc123/../x','releases/abc123/provenance/%2e%2e/x','releases/abc123/provenance/x?next=1','releases/abc123\\provenance\\x','releases/other/provenance/x'])assert.throws(()=>result.validateReleaseRelativePath(bad,{releaseId:'abc123',kind:'receipt'}));});
test('flash remains default and status has no controls',async()=>{const h=await html();assert.match(h,/id="flashTab"[^>]*aria-selected="true"/);assert.doesNotMatch(h.match(/id="statusView"[\s\S]*?<\/section>/)?.[0]||'',/button[^>]*>Install|serial/i)});
test('tab navigation styles active, focus, laptop layout and reduced-motion states',async()=>{const css=await readFile('dist/styles.css','utf8');for(const selector of ['.masthead','#maintainer-nav button[aria-selected="true"]','#maintainer-nav button:focus-visible','--shell:1120px','grid-template-columns:repeat(3,minmax(0,1fr))','@media (prefers-reduced-motion:reduce)','#statusView'])assert.match(css,new RegExp(selector.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));});
test('tab navigation keeps only the selected tab in the keyboard tab order',async()=>{const h=await html();assert.match(h,/id="flashTab"[^>]*tabindex="0"/);assert.match(h,/id="statusTab"[^>]*tabindex="-1"/);});
test('header and status share the centered shell geometry',async()=>{const css=await readFile('dist/styles.css','utf8');assert.match(css,/--content-shell:900px/);assert.match(css,/masthead\{[^}]*var\(--content-shell\)/);assert.match(css,/#statusView\{max-width:var\(--content-shell\);padding-left:0;padding-right:0/);assert.match(css,/@media \(max-width:760px\)[^}]*#statusView\{padding:28px 14px 44px/);});
