import test from 'node:test'; import assert from 'node:assert/strict'; import {readFile} from 'node:fs/promises'; import {spawnSync} from 'node:child_process';
test('browser graph has no node imports',async()=>{for(const f of ['app.mjs','local-flash.mjs','profiles.mjs','firmware-ui.mjs','device-identity.mjs','safety-contract.mjs'])assert.doesNotMatch(await readFile(`easy-flash/${f}`,'utf8'),/node:/)});
test('static build complete',async()=>{for(const f of ['dist/index.html','dist/current.json','dist/_headers'])await readFile(f)});
test('support guidance exists',async()=>assert.match(await readFile('easy-flash/index.html','utf8'),/Chrome|Edge|serial/i));
test('beginner UI has no confirmation checkbox and hidden UI is globally absent',async()=>{const [html,css]=await Promise.all([readFile('easy-flash/index.html','utf8'),readFile('easy-flash/styles.css','utf8')]);assert.doesNotMatch(html,/physicalConfirmation|confirmedPrintedModel|type="checkbox"/);assert.match(css,/\[hidden\]\s*\{\s*display\s*:\s*none\s*!important\s*\}/i)});
test('narrow flex and card content can shrink and wrap',async()=>{const css=await readFile('easy-flash/styles.css','utf8');assert.match(css,/\.controller-state\s*>\s*div[^}]*min-width\s*:\s*0/i);assert.match(css,/\.device-select[^}]*min-inline-size\s*:\s*0/i);assert.match(css,/overflow-wrap\s*:\s*(?:anywhere|break-word)/i)});
test('mobile masthead keeps all three tabs inside the viewport',async()=>{const [html,css]=await Promise.all([readFile('easy-flash/index.html','utf8'),readFile('easy-flash/styles.css','utf8')]);assert.match(html,/id="flashTab"[\s\S]*id="statusTab"[\s\S]*id="diagnoseTab"/);assert.match(css,/@media\s*\(max-width:760px\)[\s\S]*#maintainer-nav button\{[^}]*min-width:0[^}]*padding:6px 7px/i)});
test('Easy Flash identity uses the EZ spectrum mark with WLEDTubes product naming',async()=>{const [html,css]=await Promise.all([readFile('easy-flash/index.html','utf8'),readFile('easy-flash/styles.css','utf8')]);assert.match(html,/<span class="mark">EZ<\/span>/);assert.match(html,/<strong>WLEDTubes<\/strong><small>Easy Flash<\/small>/);assert.match(css,/--rainbow-spectrum:/);assert.match(css,/--spectrum-v:|--spectrum-c:/);assert.match(css,/--orange:/)});
test('shared rails and overflow guard remain explicit',async()=>{const [html,css]=await Promise.all([readFile('easy-flash/index.html','utf8'),readFile('easy-flash/styles.css','utf8')]);assert.match(css,/html,body\s*\{[^}]*overflow-x\s*:\s*hidden/i);assert.match(css,/main,#statusView,#diagnoseView\s*\{[^}]*max-width\s*:\s*900px/i);assert.match(html,/id="flashView"/);assert.match(html,/id="diagnoseView"/);assert.match(html,/id="statusView"/)});
test('public Flash UI exposes no multi-device action, OTA guidance, or teaser',async()=>{
 const paths=['easy-flash','dist','private-candidates/pr70-f0ccd8b2/site'];
 const files=await Promise.all(paths.flatMap(path=>['index.html','app.mjs','styles.css'].map(file=>readFile(`${path}/${file}`,'utf8'))));
 for(const source of files)assert.doesNotMatch(source,/migrationCard|migrationSummary|otaStateMessage|setOtaState|bridge-ready|STEP 2 · OTA GUIDANCE|Flash multiple devices|supported laptop workflow|ota-guidance|migration-card/i);
});
test('built static graph consumes current manifest and artifact without an API dependency',async()=>{const graph=(await Promise.all(['app.mjs','hosted-release.mjs','local-flash.mjs'].map(f=>readFile(`dist/${f}`,'utf8')))).join('\n');assert.doesNotMatch(graph,/\/api\//);assert.match(graph,/current\.json/);assert.match(graph,/manifest\.json/);assert.match(graph,/artifact\.url/)});
test('browser modules import without browser globals',()=>{const result=spawnSync(process.execPath,['--input-type=module','--eval',"delete globalThis.navigator; delete globalThis.window; await import('./easy-flash/local-flash.mjs?no-browser-globals')"],{encoding:'utf8'});assert.equal(result.status,0,result.stderr)});
