import * as defaultFlash from "./local-flash.mjs";
import {loadHostedRelease,selectHostedTarget} from "./hosted-release.mjs";
import {chipFamily} from "./safety-contract.mjs";
import {createDiagnoseRuntime,diagnosePresentation} from "./diagnose.mjs";

const INSTALL_ACTIONS={"quinled-dig2go":"Install Dig2Go firmware","athom-c3-tubes":"Install Athom C3 firmware","waveshare-s3-tubes-remote":"Install Waveshare S3 firmware"};
const CONNECT_ACTIONS={"quinled-dig2go":"Connect Dig2Go","athom-c3-tubes":"Connect Athom C3","waveshare-s3-tubes-remote":"Connect Waveshare S3"};
const shortTarget=id=>({"quinled-dig2go":"Dig2Go","athom-c3-tubes":"Athom C3","waveshare-s3-tubes-remote":"Waveshare S3"}[id]||id);

/** Render the complete Flash shell. No async helper may mutate Flash visibility directly. */
export function renderFlashState(ui,state,payload={}) {
  const choose=state==="choose", connecting=state==="connecting", connected=state==="connected", writing=state==="installing"||state==="finishing", result=["success","mismatch","error"].includes(state);
  const set=(node,hidden)=>{if(node)node.hidden=hidden};
  set(ui.installCard,result); set(ui.options,!choose&&!connecting); set(ui.state,choose||result);
  set(ui.status,choose||result); set(ui.advanced,!choose); set(ui.connect,!choose); set(ui.install,!connected&&!writing); set(ui.back,!(connected||choose)); set(ui.result,!result);
  ui.steps?.forEach((step,i)=>{const active=state==="choose"?0:["connecting","connected"].includes(state)?1:["installing","finishing"].includes(state)?2:3;step.toggleAttribute?.("aria-current",i===active);if(i===active)step.setAttribute?.("aria-current","step");});
  if(ui.title)ui.title.textContent=result?(state==="success"?"Firmware installed":"Install needs attention"):state==="connected"?`${shortTarget(payload.targetId)} connected`:state==="choose"?"Install firmware":`Installing`;
  if(ui.instruction)ui.instruction.textContent=choose?"Select the controller you plugged in. Chrome will ask which USB device to use.":payload.instruction||"";
  if(ui.status){ui.status.textContent=payload.status||"";ui.state.className=`status-banner ${payload.tone||"neutral"}`;}
  if(ui.stateTitle)ui.stateTitle.textContent=payload.stateTitle||"";
  if(ui.connect)ui.connect.textContent=choose?(CONNECT_ACTIONS[payload.selectedId]||"Connect"):"Connect";
  if(ui.install){ui.install.textContent=payload.progress??(INSTALL_ACTIONS[payload.targetId]||"Install");ui.install.disabled=state!=="connected"&&!writing;}
  if(ui.resultTitle)ui.resultTitle.textContent=state==="success"?"You did it!":state==="mismatch"?"Installed firmware did not match":"Install stopped";
  if(ui.resultMessage)ui.resultMessage.textContent=payload.message||"";
  if(ui.resultNext)ui.resultNext.textContent=payload.next||"";
  set(ui.resultDiagnose,state!=="mismatch");
  if(ui.resultDone)ui.resultDone.hidden=!result;
}

export function initEasyFlash({document:doc=document,navigator:navigatorRef=globalThis.navigator,isSecureContext=globalThis.isSecureContext,releaseLoader=loadHostedRelease,fetchImpl=globalThis.fetch,flash=defaultFlash,diagnoseRuntime=createDiagnoseRuntime({serial:navigatorRef?.serial})}={}) {
 const $=s=>doc.querySelector(s),ui={connect:$("#connect"),back:$("#back"),install:$("#install"),gate:$("#browserGate"),gateMessage:$("#browserGateMessage"),options:$("#deviceOptions"),deviceSelect:$("#deviceSelect"),installCard:$(".install-card"),steps:[...(doc.querySelectorAll?.(".state-rail span")||[])],state:$("#controllerState"),stateTitle:$("#controllerStateTitle"),status:$("#controllerStatus"),title:$("#installTitle"),instruction:$("#instruction"),advanced:$("#advancedDetails"),result:$("#resultPanel"),resultTitle:$("#resultTitle"),resultMessage:$("#resultMessage"),resultNext:$("#resultNext"),resultDone:$("#resultDone"),resultDiagnose:$("#resultDiagnose")};
 const diagnose={inspect:$("#diagnoseInspect"),state:$("#diagnoseState"),title:$("#diagnoseTitle"),message:$("#diagnoseMessage"),technical:$("#diagnoseTechnical"),facts:$("#diagnoseFacts")};const tabs=[$("#flashTab"),$("#diagnoseTab"),$("#statusTab")].filter(Boolean),views=[$("#flashView"),$("#diagnoseView"),$("#statusView")].filter(Boolean);
 let release=null,selection=null,state="choose";
 const browserIssue=()=>{if(!isSecureContext)return "Easy Flash must be opened over HTTPS. Reopen this exact URL over HTTPS in Chrome or Edge on a computer.";const ua=String(navigatorRef?.userAgent||"").toLowerCase();return (/safari/.test(ua)&&!/chrome|crios|edg/.test(ua))||/firefox|fxios/.test(ua)||!navigatorRef?.serial?.requestPort?"This browser cannot connect to the controller. Reopen this exact URL in Chrome or Edge on a computer.":null;};
 const transition=(next,payload={})=>{state=next;renderFlashState(ui,next,payload);};
 function renderOptions(catalog){if(!ui.options)return;ui.options.replaceChildren(...catalog.map(({variant})=>{const label=doc.createElement("label"),input=doc.createElement("input"),span=doc.createElement("span"),strong=doc.createElement("strong"),small=doc.createElement("small");label.className="device-option";input.type="radio";input.name="deviceChoice";input.value=variant.id;input.checked=variant.id==="quinled-dig2go";strong.textContent=variant.target.printedModel;small.textContent="Tubes v14";span.append(strong,small);label.append(input,span);input.addEventListener("change",()=>renderFlashState(ui,state,{selectedId:input.value}));return label;}));}
 const selected=()=>selectHostedTarget(release.catalog,ui.options?.querySelector?.("input[name=deviceChoice]:checked")?.value||"quinled-dig2go");
 async function connect(){if(!release)return;transition("connecting",{status:"Choose the USB device in Chrome…",tone:"neutral"});try{const evidence=await flash.connectToController({onStatus:status=>transition("connecting",{status,tone:"neutral"})});const chosen=selected();if(chipFamily(evidence.chipName)!==chipFamily(chosen.variant.target.chip))throw Error(`Detected ${evidence.chipName} does not match selected ${chosen.variant.target.printedModel}`);const canonical={releaseId:release.releaseId,...chosen};selection={...canonical,evidence:flash.bindConnectedController({evidence,variant:canonical.variant,artifact:canonical.artifact})};transition("connected",{targetId:canonical.variant.id,stateTitle:`${chipFamily(evidence.chipName)} detected`,status:`${chipFamily(evidence.chipName)} detected`,tone:"positive",instruction:`Confirm the board says ${canonical.variant.target.printedModel}. Nothing is written until you choose Install.`});}catch(error){await flash.disconnectController?.();selection=null;transition("choose",{status:error.name==="NotFoundError"?"Nothing connected. No changes were made.":error.message,tone:error.name==="NotFoundError"?"neutral":"attention"});}}
 async function back(){await flash.disconnectController?.();selection=null;transition("choose");}
 async function install(){if(!selection)return;const current=selection;transition("installing",{targetId:current.variant.id,progress:"Installing…",status:"Writing firmware…",tone:"progress"});try{const result=await flash.installConnectedController({variant:current,artifact:current.artifact,sessionToken:current.evidence.token,port:current.evidence.port,candidateAction:{targetId:current.variant.id,label:INSTALL_ACTIONS[current.variant.id],artifactSha256:current.artifact.sha256,sessionToken:current.evidence.token,port:current.evidence.port},onStatus:status=>transition("installing",{targetId:current.variant.id,status,tone:"progress"}),onReceipt:()=>{},onProgress:p=>transition("installing",{targetId:current.variant.id,progress:`Installing… ${p}%`,status:"Writing firmware…",tone:"progress"})});const verification=result.verification||{status:"verified"};if(verification.status==="mismatch")transition("mismatch",{message:"Easy Flash detected different firmware after the controller restarted. Nothing was rewritten.",next:"Use Diagnose controller to inspect it.",tone:"attention"});else transition("success",{message:"Firmware is installed and the controller restarted.",next:"Next, unplug USB, connect your lights, and power the controller normally.",tone:"positive"});selection=null;}catch(error){transition("error",{message:error.message,next:"Reconnect the controller and try again.",tone:"attention"});}}
 function done(){selection=null;transition("choose");ui.connect?.focus?.();}
 function diagnoseResult(){selectTab(tabs.find(t=>t.id==="diagnoseTab"));}
 async function inspect(){diagnose.inspect.disabled=true;diagnose.state.hidden=false;try{const r=await diagnoseRuntime.inspect({onStatus:m=>diagnose.message.textContent=m}),v=diagnosePresentation(r);diagnose.state.className=`status-banner ${v.tone}`;diagnose.title.textContent=v.label;diagnose.message.textContent=v.summary;}catch(e){diagnose.state.className="status-banner attention";diagnose.title.textContent="Report needs attention";diagnose.message.textContent=e.message;}finally{diagnose.inspect.disabled=false;}}
 function selectTab(tab){for(const [i,t] of tabs.entries()){t.setAttribute("aria-selected",String(t===tab));t.tabIndex=t===tab?0:-1;}for(const v of views)v.hidden=v.getAttribute("aria-labelledby")!==tab?.id;if(tab?.id!=="flashTab"){selection=null;flash.disconnectController?.();}}
 tabs.forEach((t,index)=>{t.addEventListener("click",()=>selectTab(t));t.addEventListener("keydown",event=>{let next;if(event.key==="ArrowRight"||event.key==="ArrowLeft")next=(index+(event.key==="ArrowRight"?1:tabs.length-1))%tabs.length;else if(event.key==="Home")next=0;else if(event.key==="End")next=tabs.length-1;else return;event.preventDefault();tabs[next].focus();selectTab(tabs[next]);});});diagnose.inspect?.addEventListener("click",inspect);ui.connect?.addEventListener("click",connect);ui.back?.addEventListener("click",back);ui.install?.addEventListener("click",install);ui.resultDone?.addEventListener("click",done);ui.resultDiagnose?.addEventListener("click",diagnoseResult);flash.setInvalidationHandler?.(()=>{selection=null;transition("choose");});
 transition("choose");const issue=browserIssue();if(issue){ui.gate.hidden=false;ui.gateMessage.textContent=issue;ui.connect.disabled=true;ui.connect.hidden=true;diagnose.inspect&&(diagnose.inspect.disabled=true,diagnose.inspect.hidden=true);}releaseLoader({fetchImpl,baseUrl:doc.baseURI||import.meta.url}).then(v=>{release=v;renderOptions(v.catalog);}).catch(e=>transition("error",{message:e.message,tone:"attention"}));return {connect,install,inspect,selectTab,getSelection:()=>selection,renderFlashState:transition};
}
if(typeof document!=="undefined")initEasyFlash();
