import * as defaultFlash from "./local-flash.mjs";
import { loadHostedRelease } from "./hosted-release.mjs";
import { createDiagnoseRuntime, diagnoseSummary } from "./diagnose.mjs";

// AI: below section was generated by an AI
export function initEasyFlash({document:doc=document,navigator:navigatorRef=globalThis.navigator,isSecureContext=globalThis.isSecureContext,releaseLoader=loadHostedRelease,fetchImpl=globalThis.fetch,flash=defaultFlash}={}) {
	const $=(selector)=>doc.querySelector(selector);
	const ui={connect:$("#connect"),install:$("#install"),deviceSelect:$("#deviceSelect"),deviceOptions:$("#deviceOptions"),deviceNote:$("#selectedDeviceNote"),confirmation:$("#physicalConfirmation"),confirmed:$("#confirmedDig2Go"),state:$("#controllerState"),status:$("#controllerStatus"),title:$("#installTitle"),instruction:$("#instruction"),note:$("#actionNote"),details:$("#technicalDetails"),result:$("#resultPanel"),resultTitle:$("#resultTitle"),resultMessage:$("#resultMessage")};
	const diagnose={tab:$("#diagnoseTab"),view:$("#diagnoseView"),inspect:$("#diagnoseInspect"),state:$("#diagnoseState"),title:$("#diagnoseTitle"),message:$("#diagnoseMessage"),facts:$("#diagnoseFacts")};
	const tabs=[$("#flashTab"),$("#statusTab"),diagnose.tab].filter(Boolean),views=[$("#flashView"),$("#statusView"),diagnose.view].filter(Boolean);
	let selection=null,selectedDevice=null;
	function selectTab(tab){tabs.forEach((item)=>item.setAttribute("aria-selected",String(item===tab)));tabs.forEach((item)=>item.tabIndex=item===tab?0:-1);views.forEach((view)=>view.hidden=view.getAttribute("aria-labelledby")!==tab?.id);if(tab?.id==="statusTab")doc.dispatchEvent(new Event("easy-flash:status-selected"));}
	tabs.forEach((tab,index)=>{tab.addEventListener("click",()=>selectTab(tab));tab.addEventListener("keydown",event=>{let next;if(event.key==="ArrowRight"||event.key==="ArrowLeft")next=(index+(event.key==="ArrowRight"?1:tabs.length-1))%tabs.length;else if(event.key==="Home")next=0;else if(event.key==="End")next=tabs.length-1;else return;event.preventDefault();tabs[next].focus();selectTab(tabs[next]);});});
	const diagnoseRuntime=createDiagnoseRuntime({serial:navigatorRef?.serial});
	async function inspect(){diagnose.inspect.disabled=true;diagnose.state.className="controller-state";diagnose.title.textContent="Inspecting read-only telemetry…";try{const result=await diagnoseRuntime.inspect({onStatus:(message)=>{diagnose.message.textContent=message;}});diagnose.state.className=`controller-state ${result.state === "rescue" ? "detected" : ""}`.trim();diagnose.title.textContent=result.state === "rescue" ? "Rescue mode detected" : result.state === "telemetry" ? "Diagnostic telemetry received" : result.state === "online" ? (result.unreadable ? "Could not read controller" : "Controller looks healthy") : "Inspection unavailable";diagnose.message.textContent=diagnoseSummary(result);diagnose.facts.hidden=false;diagnose.facts.replaceChildren(...[["State",result.state], ["Target",result.target || "Unsupported / not reported"], ["Chip",result.chip || "Unsupported / not reported"], ["Button",result.button ? `${result.button}${result.buttonProblem ? " — inspect for stuck/unexpected input" : ""}` : "No button diagnostic reported"], ["USB",`${result.portInfo?.usbVendorId || "VID unavailable"} · ${result.portInfo?.usbProductId || "PID unavailable"}`]].map(([label,value])=>{const row=doc.createElement("p");row.textContent=`${label}: ${value}`;return row;}));}catch(error){diagnose.state.className="controller-state error";diagnose.title.textContent="Inspection unavailable";diagnose.message.textContent=error.name==="NotFoundError"?"No controller was selected. Connect one and try again.":error.message;}finally{diagnose.inspect.disabled=false;}}
	diagnose.inspect?.addEventListener("click",inspect);
	function fact(term,value){const row=doc.createElement("div"),dt=doc.createElement("dt"),dd=doc.createElement("dd");dt.textContent=term;dd.textContent=String(value);row.append(dt,dd);return row;}
	function showFacts(records){ui.details.replaceChildren(...records.map(([term,value])=>fact(term,value)));}
	function setStatus(message,kind=""){ui.status.textContent=message;ui.state.className=`controller-state ${kind}`.trim();}
	function confirmation(){return {asserted:ui.confirmed.checked,targetId:selection?.variant.id,printedModel:selection?.variant.target.board};}
	function installAllowed(){return Boolean(selection && selection.evidence.chipName && ui.confirmed.checked);}
	function syncInstall(){ui.install.disabled=!installAllowed();}
	function variantsOf(release){return release.catalog ? release.catalog.map(({variant})=>variant) : [release.variant];}
	function defaultVariant(release){return variantsOf(release)[0];}
	function findVariant(release,id){return variantsOf(release).find((variant)=>variant.id===id);}
	function renderDeviceOptions(release){
		if(!ui.deviceOptions)return;
		const variants=variantsOf(release);
		const records=variants.map((variant)=>{
			const label=doc.createElement("label");
			const input=doc.createElement("input");
			input.type="radio";input.name="deviceChoice";input.value=variant.id;input.id=`device-${variant.id}`;
			if(!selectedDevice) selectedDevice=variant.id;input.checked=selectedDevice===variant.id;
			input.addEventListener("change",()=>{selectedDevice=variant.id;choose(variant);});
			const span=doc.createElement("span");const strong=doc.createElement("strong");strong.textContent=variant.target.board;span.append(strong);
			label.append(input,span);label.className="device-option";
			return {id:variant.id,label,variant};
		});
		ui.deviceOptions.replaceChildren(...records.map((record)=>record.label));
	}
	function syncDeviceUi(release,variant){
		// The controller list is always shown (expanded) with the first catalog entry preselected.
		ui.deviceNote.hidden=false;ui.deviceNote.textContent=`Controller: ${variant.target.board}`;
		if(ui.deviceSelect)ui.deviceSelect.hidden=false;
	}
	function choose(variant){ if(!variant)return;ui.deviceNote.hidden=false;ui.deviceNote.textContent=`Controller: ${variant.target.board}`;setStatus(`${variant.target.board} selected. Choose Connect.`,""); }
	function resetForReconnect(message="Controller disconnected. Reconnect it before installing.") { selection=null;ui.confirmed.checked=false;ui.confirmed.disabled=false;ui.confirmation.hidden=true;ui.install.hidden=true;ui.install.disabled=true;ui.install.textContent="Install";ui.note.hidden=true;ui.connect.disabled=false;ui.connect.textContent="Connect";setStatus(message,"error");ui.connect.focus(); }
	async function loadSelection(){return releaseLoader({fetchImpl,baseUrl:doc.baseURI || import.meta.url});}
	async function connect(){
		const release=await loadSelection();const variant=selectedDevice?findVariant(release,selectedDevice):defaultVariant(release);if(!variant){setStatus("Select your controller first.","error");return;}
		ui.connect.disabled=true;ui.install.hidden=true;ui.install.disabled=true;ui.confirmation.hidden=true;ui.note.hidden=true;ui.confirmed.checked=false;ui.result.hidden=true;selection=null;setStatus("Opening the USB controller chooser…");
		try{if (!isSecureContext || !navigatorRef?.serial?.requestPort) throw new Error("Open Easy Flash in Chrome or Edge over HTTPS to use Web Serial.");const canonical=release.catalog ? {releaseId:release.releaseId,variant:findVariant(release,selectedDevice||defaultVariant(release).id),artifact:release.catalog.find(({variant})=>variant.id===(selectedDevice||defaultVariant(release).id))?.artifact} : release;if(!canonical.variant)throw new Error("Selected controller catalog entry is unavailable.");const evidence=await flash.connectToController({variant:canonical.variant,onStatus:setStatus});selection={...canonical,evidence};ui.title.textContent="Controller detected";ui.instruction.textContent=`Easy Flash identified the chip as ${evidence.chipName}, which matches the ${canonical.variant.target.board} controller. Confirm the printed label, then choose Install.`;showFacts([["Detected chip",evidence.chipName],["Chip family",evidence.chipFamily],["USB",`${evidence.portInfo.usbVendorId||"VID unavailable"} · ${evidence.portInfo.usbProductId||"PID unavailable"}`],["Controller",canonical.variant.target.board],["Firmware",canonical.variant.label],["Install","Not started"]]);ui.confirmation.hidden=false;ui.install.hidden=false;syncInstall();setStatus(`${evidence.chipName} matches the ${canonical.variant.target.board}. Confirm the printed label, then choose Install.`,"detected");ui.confirmed.focus();}catch(error){await flash.disconnectController?.();ui.title.textContent="Plug in your controller";setStatus(error.name==="NotFoundError"?"No controller was selected. Plug it in and choose Connect.":error.message,"error");}finally{ui.connect.disabled=false;ui.connect.textContent=selection?"Connect a different controller":"Connect";}}
	async function install(){if(!installAllowed())return;const current=selection;ui.install.disabled=true;ui.connect.disabled=true;ui.confirmed.disabled=true;ui.result.hidden=true;try{const result=await flash.installConnectedController({variant:current.variant,artifact:current.artifact,sessionToken:current.evidence.token,port:current.evidence.port,physicalConfirmation:confirmation(),onStatus(message){setStatus(message,"detected");},onProgress(percent){ui.install.textContent=`Installing… ${percent}%`;}});ui.title.textContent="Firmware installed";setStatus("The controller restarted. Automatic health proof is unavailable in USB mode.","detected");showFacts([["Detected chip",result.chipName],["Firmware hash",result.sha256],["Backup",result.backup],["Write evidence",result.writeEvidence || "Write call returned; no readback performed"],["Restart","Requested"],["Health",result.health]]);ui.resultTitle.textContent="Installed — check the lights";ui.resultMessage.textContent="The firmware write call returned and the controller restart was requested. Easy Flash did not read the flash back or automatically prove that WLED finished booting. If the lights do not start, reconnect and try again.";ui.result.hidden=false;ui.install.hidden=true;ui.confirmation.hidden=true;ui.note.hidden=true;selection=null;}catch(error){resetForReconnect(`Install stopped: ${error.message}. Reconnect the controller and try again.`);}finally{ui.confirmed.disabled=false;}}
	let lastRelease=null;
	flash.setInvalidationHandler?.(()=>resetForReconnect());ui.confirmed.addEventListener("change",syncInstall);ui.connect.addEventListener("click",connect);ui.install.addEventListener("click",install);
	loadSelection().then((release)=>{lastRelease=release;const primary=defaultVariant(release);renderDeviceOptions(release);selectedDevice=selectedDevice||primary.id;syncDeviceUi(release,primary);showFacts([["Firmware",primary.label],["Controller",primary.target.board],["Artifact check",`SHA-256 ${release.artifact?.sha256 || "loading…"}`],["Install","Not started"]]);}).catch((error)=>setStatus(error.message,"error")).finally(()=>{doc.documentElement.dataset.easyFlashReady="true";});
	return {connect,install,getSelection:()=>selection};
}

if (typeof document !== "undefined") initEasyFlash();
// AI: end