import { ESPLoader, Transport } from "./vendor/esptool-js/bundle.js";
import { evaluatePhysicalConfirmation, validateMergedImageBytes } from "./safety-contract.mjs";
import { failureReceipt, installReceipt, transferReceipt } from "./operation-receipts.mjs";

// AI: below section was generated by an AI
export function chipFamily(value) {
	const chip=String(value).toUpperCase().replaceAll("_","-").replace(/\s+/g,"");
	for (const family of ["ESP32-S3","ESP32-S2","ESP32-C2","ESP32-C3","ESP32-C5","ESP32-C6","ESP32-C61","ESP32-H2","ESP32-P4","ESP8266"]) if (chip.startsWith(family)) return family;
	if (chip === "ESP32" || chip.startsWith("ESP32-")) return "ESP32";
	return chip;
}

function samePortInfo(left,right) { return (left.usbVendorId ?? null)===(right.usbVendorId ?? null) && (left.usbProductId ?? null)===(right.usbProductId ?? null); }
function flashSize(bytes) { const value=bytes/(1024*1024); if (!Number.isInteger(value)) throw new Error("Unsupported manifest flash size"); return `${value}MB`; }

export function createFlashRuntime({ serial=globalThis.navigator?.serial, Loader=ESPLoader, TransportClass=Transport, fetchImpl=globalThis.fetch, cryptoImpl=globalThis.crypto, delay=(milliseconds)=>new Promise((resolve)=>setTimeout(resolve,milliseconds)) }={}) {
	let active=null; let flashInProgress=false; let invalidated=()=>{};
	async function sha256Hex(bytes) { const digest=await cryptoImpl.subtle.digest("SHA-256",bytes); return Array.from(new Uint8Array(digest),(byte)=>byte.toString(16).padStart(2,"0")).join(""); }
	async function close(session) { if (!session) return; try { await session.transport.disconnect(); } catch {} }
	async function invalidate(reason, port=null) {
		const session=active;
		if (!session || (port && session.port !== port)) return;
		active=null; await close(session); invalidated({ token:session.token,reason });
	}
	serial?.addEventListener?.("disconnect",(event)=>{ void invalidate("disconnect",event.port || event.target); });

	async function fetchVerifiedImage(variant,artifact) {
		if (!artifact.url) throw new Error("The hosted firmware URL is missing");
		const response=await fetchImpl(artifact.url,{cache:"force-cache",credentials:"same-origin"});
		if (!response.ok) { const error=new Error("Firmware image is unavailable"); error.failureStage="transport"; throw error; }
		return new Uint8Array(await response.arrayBuffer());
	}

	async function connectController({variant,onStatus}) {
		if (!serial?.requestPort) throw new Error("Open Easy Flash in the desktop app or desktop Chrome/Edge");
		if (active) await invalidate("replaced");
		onStatus("Choose the USB controller…"); const port=await serial.requestPort(); const portInfo=port.getInfo(); const transport=new TransportClass(port,true);
		try {
			const terminal={clean(){},writeLine(message){if(/chip|detect|connect/i.test(message))onStatus(message);},write(message){if(/chip|detect|connect/i.test(message))onStatus(message);}};
			const loader=new Loader({transport,baudrate:115200,terminal,debugLogging:false});
			const token=Object.freeze({ id:cryptoImpl.randomUUID ? cryptoImpl.randomUUID() : `${Date.now()}-${Math.random()}` });
			active={token,port,loader,transport,portInfo:Object.freeze({...portInfo}),variantId:variant.id};
			return {token,port,portInfo:{...portInfo},proof:"connected",exactBoard:false,chipName:null,chipFamily:null};
		} catch(error) { await close({transport}); throw error; }
	}

	async function detectController({sessionToken,port,variant,onStatus}) {
		const session=active;
		if (!session || session.token!==sessionToken || session.port!==port || session.variantId!==variant.id) throw new Error("Connect the controller again before detecting");
		if (session.chipName) throw new Error("This controller is already detected; reconnect before detecting again");
		onStatus("Identifying the controller chip…"); const chipName=await session.loader.main();
		session.chipName=chipName; session.chipFamily=chipFamily(chipName); session.exactBoard=false;
		return {token:session.token,port,chipName,chipFamily:session.chipFamily,portInfo:{...session.portInfo},proof:"chip-only",exactBoard:false};
	}

	async function installConnectedController({variant,artifact,sessionToken,port,physicalConfirmation,onStatus,onProgress,onReceipt=()=>{},beforeWrite=()=>{}}) {
		if (flashInProgress) throw new Error("An install is already running"); const session=active;
		if (!session || session.token !== sessionToken || session.port !== port || session.variantId !== variant.id) throw new Error("Connect the controller again before installing");
		if (!session.chipName) throw new Error("Detect the controller chip before installing");
		const evidence=evaluatePhysicalConfirmation(variant,session.chipName,physicalConfirmation);
		if (!evidence.admitted) throw new Error("Check the printed Dig2Go label before installing");
		flashInProgress=true; let intendedBytes=0; let failureStage="validation"; const startedAt=new Date();
		try {
			onStatus("Checking the bundled firmware…"); const image=await fetchVerifiedImage(variant,artifact); const components=await validateMergedImageBytes(variant.target,artifact,image,sha256Hex);
			const currentInfo=port.getInfo(); if (!samePortInfo(session.portInfo,currentInfo)) throw new Error("The connected USB controller changed; reconnect before installing");
			failureStage="pre-write"; const observedChip=await session.loader.main();
			if (chipFamily(observedChip)!==session.chipFamily || chipFamily(observedChip)!==chipFamily(variant.target.chip)) throw new Error("The connected controller identity changed; reconnect before installing");
			if (active !== session || session.token !== sessionToken || session.port !== port) throw new Error("The prepared controller session is no longer active");
			const fileArray=components.map((component)=>({data:image.slice(component.imageStart,component.imageStart+component.sizeBytes),address:component.offset})); intendedBytes=fileArray.reduce((sum,item)=>sum+item.data.byteLength,0);
			onReceipt(transferReceipt(variant,artifact,evidence,intendedBytes,startedAt)); beforeWrite({fileArray,sessionToken,port,evidence});
			onStatus("Backup is unavailable in this browser flow. Installing without erasing saved settings…"); failureStage="write";
			await session.loader.writeFlash({fileArray,flashMode:variant.target.flashMode||"keep",flashFreq:"keep",flashSize:flashSize(variant.target.flashSizeBytes),eraseAll:false,compress:false,reportProgress(_index,written,total){onProgress(Math.round((written/total)*100));}});
			failureStage="reset"; await session.loader.after("hard_reset"); onProgress(100); onStatus("Restarting the controller…"); await delay(3000);
			const result={chipName:session.chipName,bytesWritten:intendedBytes,sha256:artifact.sha256,boardEvidence:evidence,backup:"unavailable",writeEvidence:"Write call returned; no readback performed",readbackVerified:false,health:"unverified"}; onReceipt(installReceipt(variant,artifact,evidence,intendedBytes,startedAt)); return result;
		} catch(error) { error.failureStage ||= failureStage; error.intendedBytes=intendedBytes; const receipt=failureReceipt(variant,artifact,evidence,error,intendedBytes,startedAt); error.receipt=receipt; onReceipt(receipt); throw error; }
		finally { flashInProgress=false; if (active===session) active=null; await close(session); }
	}
	return { connectController,detectController,installConnectedController,disconnectController:()=>invalidate("manual"),setInvalidationHandler(handler){invalidated=handler || (()=>{});} };
}

const runtime=createFlashRuntime();
export const connectController=runtime.connectController;
export const detectController=runtime.detectController;
export const installConnectedController=runtime.installConnectedController;
export const disconnectController=runtime.disconnectController;
export const setInvalidationHandler=runtime.setInvalidationHandler;
export function canFlashLocally(){return globalThis.window?.isSecureContext === true && !!globalThis.navigator?.serial;}
// AI: end
