import assert from "node:assert/strict";
import test from "node:test";
import {initEasyFlash} from "../app.mjs";
import {createDiagnoseRuntime,diagnosePresentation,parseDiagnosticText} from "../diagnose.mjs";

class Element {
	constructor(doc,id=""){this.doc=doc;this.id=id;this.hidden=false;this.disabled=false;this.checked=false;this.value="";this.textContent="";this.className="";this.listeners={};this.dataset={};this.attrs={};}
	addEventListener(type,handler){(this.listeners[type]??=[]).push(handler);}
	querySelector(selector){if(this.id==="deviceOptions")return (this.children||[]).flatMap(label=>label.children||[]).find(input=>input.type==="radio"&&((selector.includes(":checked")&&input.checked)||selector.includes("input[name=deviceChoice]")))||null;return this.doc.querySelector(selector);}
	dispatch(type,event={}){for(const handler of this.listeners[type]||[])handler({target:this,preventDefault(){},...event});}
	focus(){this.doc.activeElement=this;}
	append(...children){this.children=[...(this.children||[]),...children];} replaceChildren(...children){this.children=children;}
	setAttribute(name,value){this.attrs[name]=String(value);}
	getAttribute(name){return this.attrs[name]??null;}
}

function fixture() {
	const doc={activeElement:null,documentElement:{dataset:{}},nodes:{},listeners:{},baseURI:"https://flash.test/",querySelector(selector){return this.nodes[selector];},createElement(){return new Element(this);},addEventListener(type,handler){(this.listeners[type]??=[]).push(handler);},dispatchEvent(event){for(const handler of this.listeners[event.type]||[])handler(event);}};
	for(const id of ["deviceOptions","selectedDeviceNote","connect","install","verify","browserGate","browserGateTitle","browserGateMessage","controllerState","controllerStateTitle","controllerStatus","installTitle","instruction","actionNote","technicalDetails","resultPanel","resultTitle","resultMessage","flashTab","diagnoseTab","statusTab","flashView","diagnoseView","statusView","diagnoseInspect","diagnoseState","diagnoseTitle","diagnoseMessage","diagnoseFacts"])doc.nodes[`#${id}`]=new Element(doc,id);
	for(const id of ["flashView","diagnoseView","statusView"])doc.nodes[`#${id}`].attrs["aria-labelledby"]=`${id.replace("View","Tab")}`;
	for(const id of ["install","verify","actionNote","resultPanel","diagnoseView","statusView","diagnoseFacts"])doc.nodes[`#${id}`].hidden=true;doc.nodes["#browserGateTitle"].textContent="Easy Flash needs Chrome or Edge";
	const targets=[["quinled-dig2go","QuinLED Dig2Go","ESP32"],["athom-c3-tubes","Athom ESP32-C3 controller","ESP32-C3"],["waveshare-s3-tubes-remote","Waveshare ESP32-S3-Touch-AMOLED-2.16","ESP32-S3"]];
	const catalog=targets.map(([id,printedModel,chip])=>({variant:{id,label:printedModel,source:{commit:"a".repeat(40)},bootIdentity:{version:1,target:id,source:"a".repeat(40),release:"16.0.1",tubes:14},target:{printedModel,board:printedModel,chip}},artifact:{url:`https://flash.test/${id}.bin`,sha256:id.padEnd(64,"a")}}));
	let installs=0,verifies=0,disconnects=0,invalidator,lastArgs,inspects=0,connectError=null,verificationStatus="verified";
	const resultFor=(variant,status)=>({verification:{status,observed:status==="pending"?null:{...variant.bootIdentity,...(status==="mismatch"?{target:"athom-c3-tubes"}:{})},bytesCaptured:120},retryToken:status==="pending"?Object.freeze({id:"retry"}):null});
	let chipName="ESP32";const flash={setInvalidationHandler(handler){invalidator=handler;},async connectToController(){if(connectError)throw connectError;return {token:Object.freeze({id:"token"}),port:{id:"port"},chipName,chipFamily:chipName,portInfo:{}};},bindConnectedController({evidence,variant}){return {...evidence,variantId:variant.id};},async installConnectedController(args){installs++;lastArgs=args;args.onStatus("Restarting the controller…");args.onStatus("Verifying the controller…");args.onReceipt({stage:"awaiting-health",targetId:args.variant.id,artifactSha256:args.artifact.sha256});return {sha256:args.artifact.sha256,writeEvidence:"Write call returned",health:"unverified",...resultFor(args.variant,verificationStatus)};},async verifyWrittenController(args){verifies++;return resultFor(args.variant,verificationStatus);},async disconnectController(){disconnects++;}};
	const diagnoseRuntime={async inspect(){inspects++;return {state:"telemetry",target:null,observedTarget:null,chip:"ESP32-C3",button:"AVAILABLE",bytesCaptured:24};}};
	const app=initEasyFlash({document:doc,navigator:{serial:{requestPort(){}}},isSecureContext:true,releaseLoader:async()=>({releaseId:"test",catalog}),flash,diagnoseRuntime});
	return {doc,app,flash,counts:()=>({installs,verifies,disconnects,inspects}),args:()=>lastArgs,disconnect:()=>invalidator?.(),setChip:value=>{chipName=value;const id=value==="ESP32"?"quinled-dig2go":value==="ESP32-C3"?"athom-c3-tubes":"waveshare-s3-tubes-remote";(doc.nodes["#deviceOptions"].children||[]).forEach(label=>{const input=label.children?.[0];if(input)input.checked=input.value===id;});doc.nodes["#deviceOptions"].querySelector=()=>({value:id});},setConnectError:value=>connectError=value,setVerification:value=>verificationStatus=value};
}


test("single-device install verifies exact boot identity without public fleet migration state",async()=>{const f=fixture();await Promise.resolve();await f.app.connect();await f.app.install();assert.equal(f.doc.nodes["#resultPanel"].hidden,false);assert.equal(f.doc.nodes["#installTitle"].textContent,"Firmware installed");assert.equal(f.doc.nodes["#resultTitle"].textContent,"Done — ready to use");assert.equal(f.doc.nodes["#resultMessage"].textContent,"Firmware installed and the controller restarted successfully.");assert.equal(f.app.getSelection(),null);for(const selector of ["#migrationCard","#migrationSummary","#otaStateMessage"])assert.equal(f.doc.nodes[selector],undefined);});

test("pending verification offers read-only retry and retry never installs",async()=>{const f=fixture();f.setVerification("pending");await Promise.resolve();await f.app.connect();await f.app.install();assert.equal(f.doc.nodes["#verify"].hidden,false);assert.equal(f.doc.nodes["#resultTitle"].textContent,"Firmware installed");assert.equal(f.doc.nodes["#resultMessage"].textContent,"The install finished, but Easy Flash could not confirm the controller restarted.");assert.equal(f.doc.nodes["#verify"].textContent,"Check again");assert.equal(f.counts().installs,1);f.setVerification("verified");await f.app.verify();assert.equal(f.doc.nodes["#resultTitle"].textContent,"Done — ready to use");assert.equal(f.counts().installs,1);assert.equal(f.counts().verifies,1);});

test("wrong exact identity reports expected and observed without rewrite",async()=>{const f=fixture();f.setVerification("mismatch");await Promise.resolve();await f.app.connect();await f.app.install();assert.equal(f.doc.nodes["#resultTitle"].textContent,"Installed firmware did not match");assert.equal(f.doc.nodes["#verify"].hidden,true);assert.equal(f.counts().installs,1);});

test("Connect is the sole initial primary and each exact target gets one printed-label check",async()=>{for(const [chip,id,label,model] of [["ESP32","quinled-dig2go","Install Dig2Go firmware","QuinLED Dig2Go"],["ESP32-C3","athom-c3-tubes","Install Athom C3 firmware","Athom ESP32-C3 controller"],["ESP32-S3","waveshare-s3-tubes-remote","Install Waveshare S3 firmware","Waveshare ESP32-S3-Touch-AMOLED-2.16"]]){const f=fixture();await Promise.resolve();f.setChip(chip);assert.equal(f.app.getSelection(),null);assert.notEqual(f.doc.nodes["#connect"].className,"secondary");assert.equal(f.doc.nodes["#install"].hidden,true);await f.app.connect();assert.equal(f.app.getSelection().variant.id,id);assert.match(f.app.getSelection().artifact.url,new RegExp(id));assert.equal(f.doc.nodes["#install"].textContent,label);assert.equal(f.doc.nodes["#install"].hidden,false);assert.equal(f.doc.nodes["#install"].disabled,false);assert.equal(f.doc.nodes["#connect"].hidden,true);assert.match(f.doc.nodes["#instruction"].textContent,new RegExp(`${model} is ready`));assert.match(f.doc.nodes["#actionNote"].textContent,new RegExp(`Check that the board says ${model}`));assert.equal(`${f.doc.nodes["#instruction"].textContent} ${f.doc.nodes["#actionNote"].textContent}`.match(/Confirm the printed/g),null);assert.equal(f.doc.nodes["#controllerStateTitle"].textContent,"ESP32 detected");}});

test("unsupported detection fails closed without Install",async()=>{const f=fixture();f.setChip("ESP32-C6");await Promise.resolve();await f.app.connect();assert.equal(f.app.getSelection(),null);assert.equal(f.doc.nodes["#install"].hidden,true);assert.match(f.doc.nodes["#controllerStatus"].textContent,/unsupported|does not match/i);});
test("unsupported browser gate disables serial actions but leaves status available",async()=>{const f=fixture();const nav={userAgent:"Mozilla/5.0 Safari/605.1",serial:{requestPort(){}}};initEasyFlash({document:f.doc,navigator:nav,isSecureContext:true,releaseLoader:async()=>({releaseId:"test",catalog:[]}),flash:f.flash,diagnoseRuntime:f.diagnoseRuntime});await Promise.resolve();assert.equal(f.doc.nodes["#browserGate"].hidden,false);assert.equal(f.doc.nodes["#browserGateTitle"].textContent,"Easy Flash needs Chrome or Edge");assert.match(f.doc.nodes["#browserGateMessage"].textContent,/This browser cannot connect/);assert.equal(f.doc.nodes["#connect"].hidden,true);assert.equal(f.doc.nodes["#diagnoseInspect"].hidden,true);assert.equal(f.doc.nodes["#statusTab"].hidden,false);});
test("insecure context gets distinct HTTPS guidance",async()=>{const f=fixture();initEasyFlash({document:f.doc,navigator:{userAgent:"Chrome",serial:{requestPort(){}}},isSecureContext:false,releaseLoader:async()=>({releaseId:"test",catalog:[]}),flash:f.flash,diagnoseRuntime:f.diagnoseRuntime});await Promise.resolve();assert.match(f.doc.nodes["#browserGateMessage"].textContent,/over HTTPS/);assert.doesNotMatch(f.doc.nodes["#browserGateMessage"].textContent,/This browser cannot connect/);});
test("Connect never writes and the exact candidate action admits Install",async()=>{const f=fixture();await Promise.resolve();await f.app.connect();assert.equal(f.counts().installs,0);await f.app.install();assert.equal(f.counts().installs,1);assert.equal(f.args().candidateAction.targetId,"quinled-dig2go");assert.equal(f.args().candidateAction.label,"Install Dig2Go firmware");assert.equal(f.args().candidateAction.artifactSha256,f.app.getSelection()?.artifact.sha256 ?? f.args().artifact.sha256);});

test("tab selection never touches serial and leaving Flash invalidates prepared install state",async()=>{const f=fixture();await Promise.resolve();await f.app.connect();const diagnose=f.doc.nodes["#diagnoseTab"];f.app.selectTab(diagnose);assert.equal(f.app.getSelection(),null);assert.deepEqual(f.counts(),{installs:0,verifies:0,disconnects:0,inspects:0});await f.app.install();assert.equal(f.counts().installs,0);assert.equal(f.doc.nodes["#diagnoseView"].hidden,false);});

test("Status selection remains serial-free and explicit Inspect uses its own lifecycle",async()=>{const f=fixture();await Promise.resolve();f.app.selectTab(f.doc.nodes["#statusTab"]);assert.deepEqual(f.counts(),{installs:0,verifies:0,disconnects:0,inspects:0});await f.app.inspect();assert.deepEqual(f.counts(),{installs:0,verifies:0,disconnects:1,inspects:1});assert.match(f.doc.nodes["#diagnoseFacts"].children.at(-1).textContent,/Captured bytes:/);});

test("keyboard tabs wrap, support Home/End, and keep one tab in order",async()=>{const f=fixture(),tabs=[f.doc.nodes["#flashTab"],f.doc.nodes["#diagnoseTab"],f.doc.nodes["#statusTab"]];tabs[0].dispatch("keydown",{key:"ArrowLeft"});assert.equal(f.doc.activeElement,tabs[2]);assert.equal(tabs[2].tabIndex,0);tabs[2].dispatch("keydown",{key:"Home"});assert.equal(f.doc.activeElement,tabs[0]);tabs[0].dispatch("keydown",{key:"End"});assert.equal(f.doc.activeElement,tabs[2]);});

test("disconnect and reconnect clear stale candidate action state",async()=>{const f=fixture();await Promise.resolve();await f.app.connect();const stale=f.app.getSelection();f.disconnect();assert.equal(f.app.getSelection(),null);await f.app.install();assert.equal(f.counts().installs,0);await f.app.connect();assert.notEqual(f.app.getSelection(),stale);assert.equal(f.doc.nodes["#install"].textContent,"Install Dig2Go firmware");});
test("cancelled reconnect clears stale presentation and leaves no Install",async()=>{const f=fixture();await Promise.resolve();await f.app.connect();assert.match(f.doc.nodes["#actionNote"].textContent,/Check that the board says/i);const error=Object.assign(Error("cancelled"),{name:"NotFoundError"});f.setConnectError(error);await f.app.connect();assert.equal(f.app.getSelection(),null);assert.equal(f.doc.nodes["#install"].hidden,true);assert.equal(f.doc.nodes["#installTitle"].textContent,"Choose your controller");assert.doesNotMatch(f.doc.nodes["#instruction"].textContent,/cannot prove|ESP32/i);const details=f.doc.nodes["#technicalDetails"].children.flatMap(row=>row.children||[]).map(node=>node.textContent).join(" ");assert.doesNotMatch(details,/artifact|sha-256/i);});

function mockPort({chunks=[],rejectRead=false,hang=false}={}){let released=false,closed=false,cancelled=false,isOpen=false;const reader={async read(){if(rejectRead)throw Error("device disconnected");if(hang)return new Promise(()=>{});const chunk=chunks.shift();return chunk===undefined?{done:true}:{value:new TextEncoder().encode(chunk),done:false};},releaseLock(){released=true;},async cancel(){cancelled=true;}};return {get readable(){return isOpen?{getReader:()=>reader}:null;},async open(options){this.openOptions=options;isOpen=true;},async close(){closed=true;},getInfo:()=>({usbVendorId:1234}),state:()=>({released,closed,cancelled})};}

test("diagnose caps raw bytes before decoding complete UTF-8",async()=>{const result=await createDiagnoseRuntime({serial:{requestPort:async()=>mockPort({chunks:["éXYZ"]})},maxBytes:3}).inspect();assert.equal(result.raw,"éX");assert.equal(result.bytesCaptured,3);});

test("exact rescue/button parsing uses the latest banner and healthy clears STUCK_BUTTON",()=>{assert.equal(parseDiagnosticText("WLED rescue mode active. Flash over serial, or send 'format'/'reboot'.").rescue,true);assert.equal(parseDiagnosticText("AP mode active; no network yet").rescue,false);const result=parseDiagnosticText("WLED button diagnostics: STUCK_BUTTON\nWLED button diagnostics: healthy");assert.equal(result.buttonProblem,false);assert.equal(result.buttonDiagnostics,"healthy");for(const healthy of ["AVAILABLE","INACTIVE","healthy"])assert.equal(parseDiagnosticText(`WLED button diagnostics: ${healthy}`).buttonProblem,false);});

test("exact target reports classify three carriers but generic C3/S3 chips remain Unknown",()=>{for(const name of ["QuinLED Dig2Go","Athom ESP32-C3 controller","Waveshare ESP32-S3-Touch-AMOLED-2.16"])assert.equal(parseDiagnosticText(`model: ${name}`).target,name);for(const chip of ["ESP32-C3","ESP32-S3"])assert.deepEqual([parseDiagnosticText(`chip: ${chip}`).target,parseDiagnosticText(`chip: ${chip}`).targetIdentity],[null,"unknown"]);});

test("timeout, disconnect, and chooser cancellation cleanly stop without writes",async()=>{const timed=mockPort({hang:true}),result=await createDiagnoseRuntime({serial:{requestPort:async()=>timed},timeoutMs:5}).inspect();assert.equal(result.state,"unsupported");assert.deepEqual(timed.state(),{released:true,closed:true,cancelled:true});const disconnected=mockPort({rejectRead:true}),lost=await createDiagnoseRuntime({serial:{requestPort:async()=>disconnected}}).inspect();assert.equal(lost.state,"unsupported");assert.deepEqual(disconnected.state(),{released:true,closed:true,cancelled:false});const error=Object.assign(Error("cancelled"),{name:"NotFoundError"});await assert.rejects(createDiagnoseRuntime({serial:{requestPort:async()=>{throw error;}}}).inspect(),{name:"NotFoundError"});});

test("Diagnose presentation is grounded USB-only copy for every stoplight state",()=>{const cases=[
 [{},["yellow","No diagnostic report","Easy Flash opened the USB device, but it did not send a diagnostic report. This can happen when the installed firmware does not support Diagnose.","Try again"]],
 [{bytesCaptured:3},["yellow","Report not recognized","The USB device sent data, but Easy Flash could not read it as a diagnostic report.","Try again"]],
 [{state:"telemetry",target:"Dig2Go",chip:"ESP32",buttonDiagnostics:"healthy"},["green","Looks healthy","The USB device sent a valid diagnostic report and did not report a problem.","Check again"]],
 [{state:"rescue"},["red","Recovery mode reported","The USB device reported recovery mode.","Check again"]],
 [{buttonProblem:true},["red","Stuck button reported","The USB device reported a stuck button.","Check again"]]
 ];for(const [input,[tone,label,summary,action]] of cases){const view=diagnosePresentation(input);assert.deepEqual([view.tone,view.label,view.summary,view.action],[tone,label,summary,action]);assert.doesNotMatch(`${view.label} ${view.summary} ${view.next}`,/\b(network|lights|LED|telemetry|inspection|condition|retry)\b/i);}});
