// AI: below section was generated by an AI
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { readFile } from "node:fs/promises";
import test from "node:test";

const require = createRequire(import.meta.url);
const policy = require("../desktop/security-policy.cjs");
const root = new URL("../../", import.meta.url);

test("desktop route policy exposes only the fixed local application surface", () => {
	assert.equal(policy.normalizeAppPath("wledtubes://easy-flash/"), "/index.html");
	assert.equal(policy.normalizeAppPath("wledtubes://easy-flash/app.mjs"), "/app.mjs");
	assert.equal(policy.normalizeAppPath("https://example.com/app.mjs"), null);
	assert.equal(policy.normalizeAppPath("wledtubes://other/app.mjs"), null);
	assert.equal(policy.normalizeAppPath("wledtubes://easy-flash/%2e%2e/package.json"), null);
	assert.equal(policy.STATIC_FILES.has("/server.mjs"), false);
	assert.equal(policy.STATIC_FILES.has("/vendor/esptool-js/bundle.js"), true);
});

test("desktop CSP and bootstrap lock down remote content and privileged renderer APIs", async () => {
	const main = await readFile(new URL("../desktop/main.cjs", import.meta.url), "utf8");
	for (const directive of ["default-src 'self'", "connect-src 'self'", "object-src 'none'", "frame-ancestors 'none'"]) assert.match(policy.CSP, new RegExp(directive.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
	assert.match(main, /contextIsolation: true/);
	assert.match(main, /sandbox: true/);
	assert.match(main, /nodeIntegration: false/);
	assert.match(main, /devTools: !app\.isPackaged/);
	assert.match(main, /setWindowOpenHandler\(\(\) => \(\{ action: "deny" \}\)\)/);
	assert.match(main, /select-serial-port/);
	assert.match(main, /http:\/\/\*\/\*.*https:\/\/\*\/\*.*file:\/\/\*\/\*/s);
	assert.match(main, /callback\(result\.response < portList\.length \? portList\[result\.response\]\.portId : ""\)/);
	assert.doesNotMatch(main, /shell\.openExternal|setDevicePermissionHandler/);
});

test("connect and explicit install remain separate", async () => {
	const appSource = await readFile(new URL("../app.mjs", import.meta.url), "utf8");
	const flashSource = await readFile(new URL("../local-flash.mjs", import.meta.url), "utf8");
	const writePath = flashSource.slice(flashSource.indexOf("async function installConnectedController"));
	assert.match(appSource, /confirmedDig2Go/);
	assert.equal((flashSource.match(/serial\.requestPort\(\)/g) || []).length, 1);
	assert.ok(flashSource.indexOf("loader.main()") < flashSource.indexOf("active={token"));
	assert.ok(writePath.indexOf("fetchVerifiedImage(variant,artifact)") < writePath.indexOf("session.loader.writeFlash"));
	assert.doesNotMatch(appSource, /autoFlash|window\.confirm/);
});

test("packaging is narrow, reproducible, and configured for macOS and Windows x64", async () => {
	const pkg = JSON.parse(await readFile(new URL("../../package.json", import.meta.url), "utf8"));
	assert.equal(pkg.devDependencies.electron, "43.4.0");
	assert.equal(pkg.devDependencies["electron-builder"], "26.15.3");
	assert.deepEqual(pkg.build.mac.target, ["dmg", "zip"]);
	assert.deepEqual(pkg.build.win.target[0].arch, ["x64"]);
	assert.ok(pkg.build.files.includes("easy-flash/artifacts/**/*"));
	assert.ok(pkg.build.files.includes("easy-flash/device-identity.mjs"));
	assert.ok(pkg.build.files.includes("LICENSE"));
	assert.ok(pkg.build.files.includes("!node_modules/**/*"));
	assert.deepEqual(pkg.build.extraResources.map(({ to }) => to), ["LICENSE.electron.txt", "LICENSES.chromium.html"]);
	assert.equal(pkg.build.files.some((path) => path.includes("wled00/html_") || path.includes("wled00/js_")), false);
	const workflow = await readFile(new URL("../../.github/workflows/easy-flash-desktop.yml", import.meta.url), "utf8");
	assert.match(workflow, /windows-2022/);
	assert.match(workflow, /npm run dist:easy-flash:win/);
});
// AI: end
