#!/usr/bin/env python3
"""Serve pre-authorized Tubes firmware to a concurrent pull-update wave."""

from __future__ import annotations

import dataclasses
import hashlib
import http.server
import pathlib
import re
import struct
import threading
import time
import urllib.parse
from typing import Dict, Mapping, Optional, Tuple


# AI: below section was generated by an AI

FIRMWARE_PATH = "/tubes/firmware.bin"
MAC_PATTERN = re.compile(r"^[0-9a-f]{12}$")
FIRMWARE_IDENTITY_MAGIC = b"TUBEUP1\0"
FIRMWARE_IDENTITY = struct.Struct("<8sBBBH3s")
ImageKey = Tuple[int, int]


@dataclasses.dataclass(frozen=True)
class FirmwareImage:
    """One validated image authorized for a compiled hardware family and variant."""

    path: pathlib.Path
    release_name: str
    md5: str
    size: int
    family: int
    variant: int
    tubes_version: int

    @classmethod
    def from_path(cls, path: pathlib.Path, release_name: str) -> "FirmwareImage":
        """Verify the embedded fleet marker and hash the image once for every response."""
        contents = path.read_bytes()
        marker_offset = contents.find(FIRMWARE_IDENTITY_MAGIC)
        if marker_offset < 0 or marker_offset + FIRMWARE_IDENTITY.size > len(contents):
            raise ValueError(f"{path} has no fleet firmware identity")
        magic, protocol, family, variant, tubes_version, reserved = FIRMWARE_IDENTITY.unpack_from(
            contents, marker_offset
        )
        if magic != FIRMWARE_IDENTITY_MAGIC or protocol != 1 or reserved != b"\0\0\0":
            raise ValueError(f"{path} has an invalid fleet firmware identity")
        digest = hashlib.md5()  # noqa: S324 - ESP32 Update supports MD5 for transfer integrity.
        digest.update(contents)
        return cls(
            path=path,
            release_name=release_name,
            md5=digest.hexdigest(),
            size=len(contents),
            family=family,
            variant=variant,
            tubes_version=tubes_version,
        )


@dataclasses.dataclass(frozen=True)
class FleetDevice:
    """A manifest identity allowed to request exactly one compiled image."""

    family: int
    variant: int


@dataclasses.dataclass(frozen=True)
class TransferResult:
    """One complete HTTP body sent to a specific stable MAC."""

    mac: str
    bytes_sent: int
    started_at: float
    completed_at: float

    @property
    def duration(self) -> float:
        return self.completed_at - self.started_at


class TransferLedger:
    """Record successful bodies across request threads without exposing mutable state."""

    def __init__(self) -> None:
        self._condition = threading.Condition()
        self._completed: Dict[str, TransferResult] = {}

    def record(self, result: TransferResult) -> None:
        """Publish a complete body only after the final byte reaches the socket."""
        with self._condition:
            self._completed[result.mac] = result
            self._condition.notify_all()

    def snapshot(self) -> Dict[str, TransferResult]:
        """Return an immutable-at-call-time view suitable for progress reporting."""
        with self._condition:
            return dict(self._completed)

    def wait_for(self, expected_macs: set[str], timeout: float) -> bool:
        """Wait until every expected MAC has received a complete body or time expires."""
        deadline = time.monotonic() + timeout
        with self._condition:
            while not expected_macs.issubset(self._completed):
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    return False
                self._condition.wait(remaining)
            return True


class FleetUpdateHTTPServer(http.server.ThreadingHTTPServer):
    """Bind an update wave to one nonce, release, manifest, and image map."""

    daemon_threads = True
    allow_reuse_address = True

    def __init__(
        self,
        address: Tuple[str, int],
        nonce: int,
        release: int,
        devices: Mapping[str, FleetDevice],
        images: Mapping[ImageKey, FirmwareImage],
    ) -> None:
        self.wave_nonce = nonce
        self.target_release = release
        self.devices = dict(devices)
        self.images = dict(images)
        self.ledger = TransferLedger()
        super().__init__(address, FleetUpdateRequestHandler)


class FleetUpdateRequestHandler(http.server.BaseHTTPRequestHandler):
    """Authorize one device identity and stream its exact image with an MD5 header."""

    server: FleetUpdateHTTPServer
    protocol_version = "HTTP/1.1"

    def do_GET(self) -> None:  # noqa: N802 - BaseHTTPRequestHandler API.
        """Reject mismatched wave metadata before opening or sending a firmware file."""
        request = urllib.parse.urlparse(self.path)
        if request.path != FIRMWARE_PATH:
            self.send_error(http.HTTPStatus.NOT_FOUND)
            return
        try:
            parameters = urllib.parse.parse_qs(request.query, strict_parsing=True)
        except ValueError:
            self.send_error(http.HTTPStatus.BAD_REQUEST, "invalid update query")
            return
        authorization = self._authorize(parameters)
        if authorization is None:
            return
        mac, image = authorization

        started_at = time.monotonic()
        self.send_response(http.HTTPStatus.OK)
        self.send_header("Content-Type", "application/octet-stream")
        self.send_header("Content-Length", str(image.size))
        self.send_header("x-MD5", image.md5)
        self.send_header("Cache-Control", "no-store")
        self.send_header("Connection", "close")
        self.end_headers()

        sent = 0
        try:
            with image.path.open("rb") as firmware:
                while chunk := firmware.read(64 * 1024):
                    self.wfile.write(chunk)
                    sent += len(chunk)
            self.wfile.flush()
        except (BrokenPipeError, ConnectionResetError):
            return
        if sent == image.size:
            self.server.ledger.record(TransferResult(
                mac=mac,
                bytes_sent=sent,
                started_at=started_at,
                completed_at=time.monotonic(),
            ))

    def _authorize(
        self,
        parameters: Mapping[str, list[str]],
    ) -> Optional[Tuple[str, FirmwareImage]]:
        """Map exact query fields to the manifest identity and its compiled image."""
        required = {"nonce", "release", "family", "variant", "mac"}
        if set(parameters) != required or any(len(parameters[key]) != 1 for key in required):
            self.send_error(http.HTTPStatus.BAD_REQUEST, "invalid update query")
            return None
        try:
            nonce = int(parameters["nonce"][0], 16)
            release = int(parameters["release"][0], 10)
            family = int(parameters["family"][0], 10)
            variant = int(parameters["variant"][0], 10)
        except ValueError:
            self.send_error(http.HTTPStatus.BAD_REQUEST, "invalid numeric field")
            return None
        mac = parameters["mac"][0].lower()
        if not MAC_PATTERN.fullmatch(mac):
            self.send_error(http.HTTPStatus.BAD_REQUEST, "invalid MAC")
            return None
        if nonce != self.server.wave_nonce or release != self.server.target_release:
            self.send_error(http.HTTPStatus.FORBIDDEN, "stale update wave")
            return None
        expected = self.server.devices.get(mac)
        if expected is None or expected != FleetDevice(family=family, variant=variant):
            self.send_error(http.HTTPStatus.FORBIDDEN, "device identity mismatch")
            return None
        image = self.server.images.get((family, variant))
        if image is None:
            self.send_error(http.HTTPStatus.NOT_FOUND, "unsupported firmware profile")
            return None
        return mac, image

    def log_message(self, format: str, *args: object) -> None:
        """Keep wave output machine-readable; the orchestrator reports its own progress."""
        return


# AI: end
