#!/usr/bin/env python3
"""Run a canary-first parallel firmware pull across a visible Tubes fleet."""

from __future__ import annotations

import argparse
import dataclasses
import json
import getpass
import os
import pathlib
import secrets
import subprocess
import sys
import threading
import time
from typing import Dict, Iterable, Mapping

import fleet_update_server as server_module
import mesh_device_report
import read_firmware_metadata


# AI: below section was generated by an AI

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[1]
DEFAULT_FIRMWARE_DIR = REPO_ROOT / "build_output" / "firmware"
MINIMUM_PULL_RELEASE = 22


@dataclasses.dataclass(frozen=True)
class ImageProfile:
    """Map a compiled family and variant to its authorized artifact identity."""

    filename: str
    release_name: str


IMAGE_PROFILES: Mapping[server_module.ImageKey, ImageProfile] = {
    (1, 0): ImageProfile("esp32_quinled_dig2go_tubes.bin", "DIG2GO_TUBES"),
    (1, 1): ImageProfile("christmas.bin", "CHRISTMAS_TUBES"),
    (1, 2): ImageProfile("golden.bin", "GOLDEN_TUBES"),
    (3, 0): ImageProfile("esp32-c3-athom_tubes.bin", "ESP32-C3_ATHOM_TUBES"),
}


def read_target_release() -> int:
    """Read the firmware's reported Tubes release from its single source of truth."""
    for line in (SCRIPT_DIR / "updater.h").read_text().splitlines():
        if line.startswith("#define RELEASE_VERSION "):
            return int(line.rsplit(maxsplit=1)[1])
    raise RuntimeError("updater.h has no RELEASE_VERSION")


def load_manifest(serial: pathlib.Path, timeout: float = 7.0) -> list[dict[str, int | str]]:
    """Request a nonce-bound manifest through the existing safe serial reader."""
    result = subprocess.run(
        [
            sys.executable,
            str(SCRIPT_DIR / "mesh_device_report.py"),
            "manifest",
            str(serial),
            "--timeout",
            str(timeout),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    manifest = json.loads(result.stdout)
    if not isinstance(manifest, list):
        raise RuntimeError("manifest command did not return a list")
    return manifest


def load_images(
    firmware_dir: pathlib.Path,
    devices: Iterable[Mapping[str, int | str]],
) -> Dict[server_module.ImageKey, server_module.FirmwareImage]:
    """Authorize only artifacts required by the manifest and verify their WLED release names."""
    needed = {(int(device["family"]), int(device["variant"])) for device in devices}
    images: Dict[server_module.ImageKey, server_module.FirmwareImage] = {}
    for key in sorted(needed):
        profile = IMAGE_PROFILES.get(key)
        if profile is None:
            raise RuntimeError(f"no pull-update image profile for family={key[0]} variant={key[1]}")
        path = firmware_dir / profile.filename
        if not path.is_file():
            raise RuntimeError(f"firmware image does not exist: {path}")
        _, embedded_release = read_firmware_metadata.read_firmware_metadata(path)
        if embedded_release != profile.release_name:
            raise RuntimeError(
                f"{path.name} contains release {embedded_release!r}, expected {profile.release_name!r}"
            )
        images[key] = server_module.FirmwareImage.from_path(path, profile.release_name)
        if (images[key].family, images[key].variant) != key:
            raise RuntimeError(
                f"{path.name} is compiled for family={images[key].family} "
                f"variant={images[key].variant}, expected family={key[0]} variant={key[1]}"
            )
        target_release = read_target_release()
        if images[key].tubes_version != target_release:
            raise RuntimeError(
                f"{path.name} contains Tubes release {images[key].tubes_version}, "
                f"expected {target_release}"
            )
    return images


def send_offer(
    serial: pathlib.Path,
    release: int,
    advertise: str,
    port: int,
    start_window_ms: int,
    target_device_id: int,
    nonce: int,
    ssid: str,
    password: str,
) -> None:
    """Send one explicit offer and require the USB controller to echo its exact nonce."""
    command = (
        f"Y{release},{advertise},{port},{start_window_ms},"
        f"{target_device_id:04X},{nonce:08X},{ssid},{password}\n"
    ).encode("utf-8")
    descriptor = mesh_device_report.open_serial(serial)
    try:
        confirmation = f"TUBE_FLEET_UPDATE nonce={nonce:08X}"
        if not mesh_device_report.send_and_confirm(descriptor, command, confirmation, 3.0):
            raise RuntimeError("USB controller did not confirm the fleet update offer")
    finally:
        os.close(descriptor)


def load_network_password(ssid: str) -> str:
    """Read the update-network secret without placing it in logs or process arguments."""
    configured = os.environ.get("TUBES_FLEET_WIFI_PASSWORD")
    if configured is not None:
        return configured
    if sys.platform == "darwin":
        result = subprocess.run(
            [
                "security",
                "find-generic-password",
                "-D",
                "AirPort network password",
                "-a",
                ssid,
                "-w",
            ],
            check=True,
            capture_output=True,
            text=True,
            timeout=10,
        )
        return result.stdout.rstrip("\n")
    return getpass.getpass(f"Password for update network {ssid}: ")


def wait_for_device_release(
    serial: pathlib.Path,
    expected: Mapping[str, Mapping[str, int | str]],
    release: int,
    timeout: float,
) -> None:
    """Require every stable MAC to rejoin with its prior hardware shape and the new release."""
    deadline = time.monotonic() + timeout
    last_problem = "no post-update manifest received"
    while time.monotonic() < deadline:
        try:
            observed = {str(device["mac"]): device for device in load_manifest(serial, 5.0)}
        except (OSError, subprocess.SubprocessError, ValueError) as error:
            last_problem = str(error)
            time.sleep(2)
            continue
        problems = []
        for mac, before in expected.items():
            after = observed.get(mac)
            if after is None:
                problems.append(f"{mac} missing")
                continue
            for field in ("family", "variant", "leds", "buses", "pin", "type"):
                if after[field] != before[field]:
                    problems.append(f"{mac} {field} changed from {before[field]} to {after[field]}")
            if int(after["tubes"]) != release:
                problems.append(f"{mac} reports release {after['tubes']}, expected {release}")
        if not problems:
            return
        last_problem = "; ".join(problems)
        time.sleep(2)
    raise RuntimeError(f"post-update mesh verification failed: {last_problem}")


def run_wave(args: argparse.Namespace) -> int:
    """Verify prerequisites, prove one canary, then update all remaining eligible devices in parallel."""
    release = read_target_release()
    manifest = load_manifest(args.serial)
    candidates = [device for device in manifest if int(device["tubes"]) < release]
    if not candidates:
        print(f"Fleet already reports release {release}; no update needed.")
        return 0
    unsupported = [device for device in candidates if int(device["tubes"]) < MINIMUM_PULL_RELEASE]
    if unsupported:
        macs = ", ".join(str(device["mac"]) for device in unsupported)
        raise RuntimeError(
            f"parallel pull requires release {MINIMUM_PULL_RELEASE} bootstrap firmware; "
            f"upgrade these devices once through the existing path: {macs}"
        )

    expected = {str(device["mac"]): device for device in candidates}
    authorized = {
        mac: server_module.FleetDevice(int(device["family"]), int(device["variant"]))
        for mac, device in expected.items()
    }
    images = load_images(args.firmware_dir, candidates)
    network_ssid = "" if args.stored_network else args.ssid
    network_password = "" if args.stored_network else load_network_password(network_ssid)
    if len(network_ssid.encode("utf-8")) + len(network_password.encode("utf-8")) > 22:
        raise RuntimeError("SSID and password exceed the protocol's combined 22-byte limit")
    if "," in network_ssid or "," in network_password:
        raise RuntimeError("SSID and password cannot contain commas in protocol version 1")
    nonce = secrets.randbits(32) or 1
    update_server = server_module.FleetUpdateHTTPServer(
        (args.bind, args.port), nonce, release, authorized, images
    )
    server_thread = threading.Thread(target=update_server.serve_forever, daemon=True)
    server_thread.start()
    actual_port = int(update_server.server_address[1])
    started_at = time.monotonic()
    try:
        if args.canary_mac:
            requested_canary = mesh_device_report.normalize_mac(args.canary_mac)
            canary = next(
                (device for device in candidates if str(device["mac"]) == requested_canary),
                None,
            )
            if canary is None:
                raise RuntimeError(f"canary {requested_canary} is not an eligible visible device")
        else:
            canary = min(candidates, key=lambda device: str(device["mac"]))
        canary_mac = str(canary["mac"])
        print(f"Canary {canary_mac}: Device ID 0x{int(canary['node']):04X}")
        send_offer(
            args.serial, release, args.advertise, actual_port, 0,
            int(canary["node"]), nonce, network_ssid, network_password,
        )
        if not update_server.ledger.wait_for({canary_mac}, args.transfer_timeout):
            raise RuntimeError(f"canary {canary_mac} did not complete its firmware download")
        wait_for_device_release(
            args.serial, {canary_mac: canary}, release, args.verify_timeout
        )
        print(f"Canary {canary_mac} verified; opening the parallel fleet wave.")

        remaining = set(expected) - {canary_mac}
        if remaining:
            send_offer(
                args.serial, release, args.advertise, actual_port,
                args.start_window_ms, 0, nonce,
                network_ssid, network_password,
            )
            if not update_server.ledger.wait_for(set(expected), args.transfer_timeout):
                completed = set(update_server.ledger.snapshot())
                missing = ", ".join(sorted(set(expected) - completed))
                raise RuntimeError(f"firmware download timed out for: {missing}")
            wait_for_device_release(args.serial, expected, release, args.verify_timeout)

        elapsed = time.monotonic() - started_at
        bytes_sent = sum(result.bytes_sent for result in update_server.ledger.snapshot().values())
        print(
            f"FLEET_PULL_COMPLETE devices={len(expected)} seconds={elapsed:.1f} "
            f"payload_mbps={(bytes_sent * 8 / elapsed / 1_000_000):.2f}"
        )
        return 0
    finally:
        update_server.shutdown()
        update_server.server_close()
        server_thread.join()


def build_parser() -> argparse.ArgumentParser:
    """Expose network and timing choices without weakening manifest authorization."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("serial", type=pathlib.Path)
    parser.add_argument("--advertise", required=True, help="LAN IPv4 address reachable by every pole")
    network = parser.add_mutually_exclusive_group(required=True)
    network.add_argument("--ssid", help="temporary 2.4 GHz update network")
    network.add_argument(
        "--stored-network",
        action="store_true",
        help="use each pole's already-configured Wi-Fi network",
    )
    parser.add_argument("--bind", default="0.0.0.0", help="local server bind address")
    parser.add_argument("--port", type=int, default=8080)
    parser.add_argument("--start-window-ms", type=int, default=5000)
    parser.add_argument("--canary-mac", help="use one visible stable MAC as the canary")
    parser.add_argument("--transfer-timeout", type=float, default=180.0)
    parser.add_argument("--verify-timeout", type=float, default=90.0)
    parser.add_argument("--firmware-dir", type=pathlib.Path, default=DEFAULT_FIRMWARE_DIR)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    if not args.serial.exists():
        raise RuntimeError(f"serial device does not exist: {args.serial}")
    if not 1 <= args.port <= 65535:
        raise RuntimeError("port must be between 1 and 65535")
    if not 0 <= args.start_window_ms <= 30000:
        raise RuntimeError("start window must be between 0 and 30000 ms")
    return run_wave(args)


# AI: end


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (RuntimeError, subprocess.SubprocessError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(1)
