#!/usr/bin/env node
import {cp,mkdir,readFile,rm,writeFile} from 'node:fs/promises';
import {basename,dirname,resolve} from 'node:path';
import {verifyBuildReceipt} from './verify-build-receipt.mjs';
import {jsonHash,sha256} from './release-provenance.mjs';
const args=process.argv.slice(2),value=name=>{const i=args.indexOf(name);return i<0?undefined:args[i+1]},release=value('--release')||process.env.EASY_FLASH_RELEASE||'provisional-pr70-f0ccd8b2';
if(!/^[a-z0-9][a-z0-9._-]*$/i.test(release))throw Error('invalid release id');const receiptPath=resolve(value('--receipt')||process.env.EASY_FLASH_BUILD_RECEIPT||'build/easy-flash-firmware/build-receipt.json'),receipt=await verifyBuildReceipt(receiptPath,{allowFixture:args.includes('--fixture')}),receiptRoot=dirname(receiptPath),out=resolve(value('--output')||process.env.EASY_FLASH_OUTPUT||'dist'),releaseRoot=resolve(out,'releases',release),provenance=resolve(releaseRoot,'provenance');
await rm(out,{recursive:true,force:true});await mkdir(resolve(releaseRoot,'firmware'),{recursive:true});await mkdir(provenance,{recursive:true});
for(const file of ['index.html','styles.css','firmware-bench.css','app.mjs','hosted-release.mjs','local-flash.mjs','boot-verification.mjs','profiles.mjs','firmware-ui.mjs','device-identity.mjs','safety-contract.mjs','operation-receipts.mjs','diagnose.mjs','p2p-seed.mjs'])await cp(resolve('easy-flash',file),resolve(out,file));await cp(resolve('easy-flash/maintainer'),resolve(out,'maintainer'),{recursive:true});await cp(resolve('easy-flash/vendor'),resolve(out,'vendor'),{recursive:true});await cp('_headers',resolve(out,'_headers'));
const contractName='update-contract.json';await cp(resolve(receiptRoot,receipt.contract.path),resolve(provenance,contractName));const variants=[];
for(const item of receipt.targets){const target=item.contractTarget,name=`${target.id}-merged.bin`,publicPath=`releases/${release}/firmware/${name}`;await cp(resolve(receiptRoot,item.artifacts.usb.path),resolve(out,publicPath));const partitionName=`${target.id}-${basename(item.partition.path)}`;await cp(resolve(receiptRoot,item.partition.path),resolve(provenance,partitionName));variants.push({id:target.id,label:`${item.printedModel} — Tubes v${item.bootIdentity.tubes}`,description:'Exact WLEDTubes PR #70 provisional hardware target.',source:receipt.source,bootIdentity:item.bootIdentity,target:{environment:item.environment,chip:target.chipFamily,board:target.board,printedModel:item.printedModel,hardwareFamily:target.hardwareFamily,flashSizeBytes:target.flashSizeBytes,flashMode:target.flashMode},status:'provisional',hardwareTested:false,partition:{csv:target.partition.csvPath,tableSha256:item.partition.sha256,otaSlot:target.partition.otaSlots[0]},artifacts:[{kind:'complete-merged-image',transport:'usb',path:publicPath,sizeBytes:item.artifacts.usb.lengthBytes,sha256:item.artifacts.usb.sha256,offset:0,components:item.artifacts.usb.components.map(c=>({name:c.id,offset:c.offset,sizeBytes:c.lengthBytes,sha256:c.sha256}))}],provenance:{partitionPath:`releases/${release}/provenance/${partitionName}`,partitionSha256:item.partition.sha256,ota:{sizeBytes:item.artifacts.ota.lengthBytes,sha256:item.artifacts.ota.sha256}}});}
const {receiptSha256:sourceReceiptDigestSha256,...sourceReceipt}=receipt,publicReceipt={schemaVersion:2,mode:receipt.mode,sourceReceiptDigestSha256,sourceReceipt,receiptDigestAlgorithm:'sha256-stable-json-v1',pathBase:'release-directory'};publicReceipt.receiptDigestSha256=jsonHash(publicReceipt);const receiptBytes=Buffer.from(JSON.stringify(publicReceipt,null,2)+'\n');await writeFile(resolve(provenance,'build-receipt.json'),receiptBytes);
const manifest={schemaVersion:2,provisional:true,promotion:'Blocked until PR #70 exact head is merged and the dependency is re-pinned to merged upstream main.',variants,provenance:{mode:receipt.mode,receiptDigestSha256:publicReceipt.receiptDigestSha256,sourceReceiptDigestSha256,contractSha256:receipt.contract.sha256,evidence:{receipt:{path:`releases/${release}/provenance/build-receipt.json`,sha256:sha256(receiptBytes)},contract:{path:`releases/${release}/provenance/${contractName}`,sha256:receipt.contract.sha256}}}};await writeFile(resolve(releaseRoot,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');await writeFile(resolve(out,'current.json'),JSON.stringify({releaseId:release,manifest:`releases/${release}/manifest.json`,generatedAt:new Date().toISOString(),provisional:true},null,2)+'\n');console.log(`built private provisional static candidate at ${out}`);
