#!/usr/bin/env node
import {createHash} from "node:crypto";
import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {containedFile,fileEvidence,jsonHash,requireHash,safeRelative} from "./release-provenance.mjs";

const args=process.argv.slice(2),value=name=>{const index=args.indexOf(name);return index<0?undefined:args[index+1];},dist=resolve(value("--dist")||process.env.EASY_FLASH_OUTPUT||"dist");
const current=JSON.parse(await readFile(resolve(dist,"current.json")));if(current.provisional!==true)throw Error("candidate is not explicitly provisional");
const prefix=`releases/${current.releaseId}/`;if(current.manifest!==`${prefix}manifest.json`)throw Error("manifest pointer mismatch");safeRelative(current.manifest,"manifest");
const releaseDir=resolve(dist,"releases",current.releaseId),manifest=JSON.parse(await readFile(await containedFile(releaseDir,"manifest.json","manifest"))),expectedMode=args.includes("--fixture")?"fixture":"provisional";
if(manifest.provisional!==true||manifest.provenance?.mode!==expectedMode)throw Error("release has wrong provisional evidence mode");
const evidenceFiles={};
for(const kind of ["receipt","contract"]){const evidence=manifest.provenance?.evidence?.[kind];safeRelative(evidence?.path,`${kind} evidence`);if(!evidence.path.startsWith(`${prefix}provenance/`))throw Error(`${kind} evidence outside immutable release`);const path=await containedFile(dist,evidence.path,`${kind} evidence`),actual=await fileEvidence(path);if(actual.sha256!==evidence.sha256)throw Error(`${kind} provenance evidence mismatch`);evidenceFiles[kind]=path;}
const publicReceipt=JSON.parse(await readFile(evidenceFiles.receipt)),publicDigest=publicReceipt.receiptDigestSha256;
delete publicReceipt.receiptDigestSha256;
if(publicReceipt.schemaVersion!==2||publicReceipt.mode!==expectedMode||jsonHash(publicReceipt)!==publicDigest||publicDigest!==manifest.provenance.receiptDigestSha256)throw Error("public receipt mode or digest mismatch");
publicReceipt.receiptDigestSha256=publicDigest;
const sourceReceipt=publicReceipt.sourceReceipt,sourceDigest=publicReceipt.sourceReceiptDigestSha256;
if(sourceReceipt?.schemaVersion!==2||sourceReceipt.mode!==expectedMode||sourceReceipt.source?.repository!=="https://github.com/SteveEisner/WLEDtubes.git"||sourceReceipt.source.clean!==true||jsonHash(sourceReceipt)!==sourceDigest||sourceDigest!==manifest.provenance.sourceReceiptDigestSha256)throw Error("source receipt mode, authority, or digest mismatch");
const contractEvidence=await fileEvidence(evidenceFiles.contract);
if(contractEvidence.sha256!==sourceReceipt.contract?.sha256||contractEvidence.sha256!==manifest.provenance.contractSha256)throw Error("contract receipt binding mismatch");
const ids=["quinled-dig2go","athom-c3-tubes","waveshare-s3-tubes-remote"];if(manifest.variants?.length!==3||JSON.stringify(manifest.variants.map(item=>item.id))!==JSON.stringify(ids))throw Error("wrong target set");
for(const variant of manifest.variants){requireHash(variant.source?.commit,"commit","commit");if(variant.source.commit!=="a17370b841cfaef2541dad5b4d7dafc49bbea800"||variant.source.repository!==sourceReceipt.source.repository||variant.source.clean!==sourceReceipt.source.clean||variant.hardwareTested!==false)throw Error("wrong source authority or hardware claim");const target=sourceReceipt.targets?.find(item=>item.targetId===variant.id);if(!target||target.environment!==variant.target.environment||target.contractTarget?.id!==variant.id||target.contractTarget.chipFamily!==variant.target.chip||target.contractTarget.board!==variant.target.board||sourceReceipt.source.commit!==variant.source.commit)throw Error("target receipt binding mismatch");if(target.partition.sha256!==variant.partition.tableSha256||target.partition.csvPath!==variant.partition.csv)throw Error("partition receipt binding mismatch");const artifact=variant.artifacts?.[0];if(artifact?.transport!=="usb"||artifact.kind!=="complete-merged-image"||artifact.offset!==0)throw Error("wrong USB artifact");safeRelative(artifact.path,"artifact path");if(artifact.path!==`${prefix}firmware/${variant.id}-merged.bin`)throw Error("artifact path outside immutable release firmware directory");if(target.artifacts.usb.sha256!==artifact.sha256||target.artifacts.usb.lengthBytes!==artifact.sizeBytes||JSON.stringify(target.artifacts.usb.components.map(item=>({name:item.id,offset:item.offset,sizeBytes:item.lengthBytes,sha256:item.sha256})))!==JSON.stringify(artifact.components))throw Error("artifact receipt binding mismatch");const file=await containedFile(releaseDir,artifact.path.slice(prefix.length),"artifact"),actual=await fileEvidence(file);if(actual.lengthBytes!==artifact.sizeBytes||actual.sha256!==artifact.sha256)throw Error("artifact mismatch");const bytes=await readFile(file);let end=0;for(const component of [...artifact.components].sort((left,right)=>left.offset-right.offset)){if(component.offset<end||component.offset+component.sizeBytes>bytes.length)throw Error("component bounds mismatch");if(createHash("sha256").update(bytes.subarray(component.offset,component.offset+component.sizeBytes)).digest("hex")!==component.sha256)throw Error("component mismatch");end=component.offset+component.sizeBytes;}if(target.artifacts.ota.lengthBytes!==variant.provenance.ota.sizeBytes||target.artifacts.ota.sha256!==variant.provenance.ota.sha256||variant.provenance.ota.sizeBytes>variant.partition.otaSlot.sizeBytes)throw Error("OTA receipt binding mismatch");}
console.log("verified 3 immutable provisional target artifacts with bounds and provenance");
