// AI: below section was generated by an AI
// Boots the existing participant-safe Easy Flash renderer from a locked local protocol.
const { app, BrowserWindow, dialog, protocol, session } = require("electron");
const { readFile } = require("node:fs/promises");
const { join } = require("node:path");
const { pathToFileURL } = require("node:url");
const { APP_ENTRY, APP_ORIGIN, CSP, STATIC_FILES, isAllowedNavigation, normalizeAppPath } = require("./security-policy.cjs");

protocol.registerSchemesAsPrivileged([{ scheme: "wledtubes", privileges: { standard: true, secure: true, supportFetchAPI: true, corsEnabled: false } }]);
app.enableSandbox();

const EASY_FLASH_ROOT = join(__dirname, "..");
const MIME_TYPES = new Map([[".html", "text/html; charset=utf-8"], [".mjs", "text/javascript; charset=utf-8"], [".js", "text/javascript; charset=utf-8"], [".css", "text/css; charset=utf-8"]]);

function response(body, status = 200, contentType = "application/octet-stream", extraHeaders = {}) {
	return new Response(body, { status, headers: { "Content-Type": contentType, "Content-Security-Policy": CSP, "X-Content-Type-Options": "nosniff", ...extraHeaders } });
}

async function loadManifestModule() {
	return import(pathToFileURL(join(EASY_FLASH_ROOT, "firmware-manifest.mjs")).href);
}

async function handleFirmwareApi(request, pathname) {
	const { loadFirmwareManifest, resolveFirmwareArtifact } = await loadManifestModule();
	if (pathname === "/api/firmware-manifest") return response(JSON.stringify(await loadFirmwareManifest()), 200, "application/json; charset=utf-8", { "Cache-Control": "no-store" });
	const match = pathname.match(/^\/api\/firmware\/([a-z0-9-]+)\/(usb|ota)$/);
	if (!match) return response("Not found", 404, "text/plain; charset=utf-8");
	const expected = {
		hardwareFamily: request.headers.get("x-easy-flash-hardware-family"),
		chip: request.headers.get("x-easy-flash-chip"),
		flashSizeBytes: Number(request.headers.get("x-easy-flash-flash-bytes")),
		partitionTableSha256: request.headers.get("x-easy-flash-partition-sha256"),
	};
	const { variant, artifact, bytes } = await resolveFirmwareArtifact(match[1], match[2], undefined, expected.hardwareFamily ? expected : null);
	const filename = `${variant.id}-${artifact.transport === "usb" ? "usb-merged" : "http-ota-app"}.bin`;
	return response(bytes, 200, "application/octet-stream", { "Cache-Control": "no-store", "Content-Disposition": `attachment; filename=\"${filename}\"`, "X-Content-SHA256": artifact.sha256 });
}

async function handleLocalRequest(request) {
	const pathname = normalizeAppPath(request.url);
	if (!pathname) return response("Forbidden", 403, "text/plain; charset=utf-8");
	try {
		if (pathname.startsWith("/api/")) return await handleFirmwareApi(request, pathname);
		if (!STATIC_FILES.has(pathname)) return response("Not found", 404, "text/plain; charset=utf-8");
		const bytes = await readFile(join(EASY_FLASH_ROOT, pathname.slice(1)));
		const extension = pathname.slice(pathname.lastIndexOf("."));
		return response(bytes, 200, MIME_TYPES.get(extension) || "application/octet-stream");
	} catch (error) {
		console.error("Easy Flash local resource error:", error.message);
		return response("Local resource unavailable", 500, "text/plain; charset=utf-8");
	}
}

function describeSerialPort(port) {
	const label = port.displayName || port.portName || "USB serial device";
	const identifiers = [port.vendorId && `VID ${port.vendorId}`, port.productId && `PID ${port.productId}`].filter(Boolean).join(" · ");
	return identifiers ? `${label} — ${identifiers}` : label;
}

function installSerialPolicy(window) {
	const appSession = session.defaultSession;
	const allowed = (permission, origin) => permission === "serial" && String(origin).replace(/\/$/, "") === APP_ORIGIN;
	appSession.setPermissionCheckHandler((_webContents, permission, requestingOrigin) => allowed(permission, requestingOrigin));
	appSession.setPermissionRequestHandler((_webContents, permission, callback, details) => callback(allowed(permission, details.requestingUrl || details.requestingOrigin)));
	appSession.webRequest.onBeforeRequest({ urls: ["http://*/*", "https://*/*", "file://*/*"] }, (_details, callback) => callback({ cancel: true }));
	appSession.on("select-serial-port", async (event, portList, _webContents, callback) => {
		event.preventDefault();
		const choices = portList.map(describeSerialPort);
		const result = await dialog.showMessageBox(window, {
			type: "question",
			title: "Select the connected controller",
			message: "Choose the USB controller you just plugged in.",
			detail: "Connecting does not install anything. Easy Flash will inspect the ESP chip first.",
			buttons: [...choices, "Cancel"],
			cancelId: choices.length,
			defaultId: choices.length,
			noLink: true,
		});
		callback(result.response < portList.length ? portList[result.response].portId : "");
	});
}

function createWindow() {
	const window = new BrowserWindow({
		width: 500,
		height: 560,
		minWidth: 440,
		minHeight: 480,
		show: false,
		autoHideMenuBar: true,
		webPreferences: { contextIsolation: true, sandbox: true, nodeIntegration: false, devTools: !app.isPackaged, webSecurity: true, allowRunningInsecureContent: false },
	});
	window.removeMenu();
	window.webContents.setWindowOpenHandler(() => ({ action: "deny" }));
	window.webContents.on("will-navigate", (event, url) => { if (!isAllowedNavigation(url)) event.preventDefault(); });
	window.webContents.on("will-attach-webview", (event) => event.preventDefault());
	window.webContents.on("before-input-event", (event, input) => { if (app.isPackaged && (input.key === "F12" || ((input.control || input.meta) && input.shift && ["I", "J", "C"].includes(input.key.toUpperCase())))) event.preventDefault(); });
	window.once("ready-to-show", () => { if (process.env.EASY_FLASH_DESKTOP_SMOKE !== "1") window.show(); });
	if (process.env.EASY_FLASH_DESKTOP_SMOKE === "1") window.webContents.once("did-finish-load", async () => {
		try {
			const result = await window.webContents.executeJavaScript(`(async () => ({ protocol: location.protocol, secure: window.isSecureContext, serial: "serial" in navigator, manifest: (await fetch("/api/firmware-manifest")).ok }))()`);
			console.log(`EASY_FLASH_SMOKE ${JSON.stringify(result)}`);
			app.exit(result.protocol === "wledtubes:" && result.secure && result.serial && result.manifest ? 0 : 1);
		} catch (error) { console.error("EASY_FLASH_SMOKE failed", error); app.exit(1); }
	});
	installSerialPolicy(window);
	window.loadURL(APP_ENTRY);
	return window;
}

app.whenReady().then(async () => {
	await protocol.handle("wledtubes", handleLocalRequest);
	createWindow();
	app.on("activate", () => { if (BrowserWindow.getAllWindows().length === 0) createWindow(); });
});
app.on("window-all-closed", () => { if (process.platform !== "darwin") app.quit(); });
// AI: end
