// AI: below section was generated by an AI
const APP_ORIGIN = "wledtubes://easy-flash";
const APP_ENTRY = `${APP_ORIGIN}/index.html`;
const CSP = [
	"default-src 'self'",
	"script-src 'self'",
	"style-src 'self'",
	"img-src 'self' data:",
	"connect-src 'self'",
	"object-src 'none'",
	"base-uri 'none'",
	"form-action 'none'",
	"frame-ancestors 'none'",
].join("; ");

const STATIC_FILES = new Set([
	"/index.html",
	"/app.mjs",
	"/profiles.mjs",
	"/firmware-ui.mjs",
	"/local-flash.mjs",
	"/device-identity.mjs",
	"/styles.css",
	"/vendor/esptool-js/bundle.js",
]);

function normalizeAppPath(urlValue) {
	if (/%(?:2e|2f|5c)/i.test(urlValue)) return null;
	const url = new URL(urlValue);
	if (url.protocol !== "wledtubes:" || url.hostname !== "easy-flash" || url.username || url.password || url.port) return null;
	let pathname;
	try { pathname = decodeURIComponent(url.pathname); } catch { return null; }
	if (pathname === "/") pathname = "/index.html";
	if (pathname.includes("\\") || pathname.split("/").includes("..")) return null;
	return pathname;
}

function isAllowedNavigation(urlValue) {
	return normalizeAppPath(urlValue) === "/index.html";
}

module.exports = { APP_ENTRY, APP_ORIGIN, CSP, STATIC_FILES, isAllowedNavigation, normalizeAppPath };
// AI: end
